"""QA for the packaged page; uses local bytes when navigation is restricted."""
from pathlib import Path
import json
from playwright.sync_api import sync_playwright, expect
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'test-results'
OUT.mkdir(exist_ok=True)
results = []
def record(label): results.append(label)
def no_overflow(page, width):
    size = page.evaluate('({scroll:document.documentElement.scrollWidth, viewport:innerWidth})')
    assert size['scroll'] <= size['viewport'] + 1, f'Overflow at {width}: {size}'
    record(f'No page overflow at {width}px')
with sync_playwright() as p:
    browser = p.chromium.launch(executable_path='/usr/bin/chromium', headless=True, args=['--no-sandbox'])
    context = browser.new_context(viewport={'width':1440,'height':1040},device_scale_factor=1)
    context.route('https://cdn.jsdelivr.net/**', lambda route: route.abort())
    page = context.new_page()
    errors = []
    page.on('pageerror', lambda err: errors.append(str(err)))
    html = (ROOT/'dist/preview.html').read_text()
    page.set_content(html, wait_until='domcontentloaded')
    expect(page.locator('.status-title')).to_have_text('Classroom check-in')
    record('Parent dashboard initializes without optional CDN')
    no_overflow(page,1440)
    page.screenshot(path=str(OUT/'desktop-hero.png'))
    page.locator('#app').screenshot(path=str(OUT/'desktop-dashboard.png'))
    page.locator('[data-hero="1"]').click()
    expect(page.locator('#hero-status')).to_have_text('The journey has begun.')
    record('Hero stage updates glass card')
    page.locator('[data-tab="journey"]').click()
    expect(page.locator('#app-content .event-list li')).to_have_count(6)
    page.locator('[data-tab="attendance"]').click()
    expect(page.locator('[data-day]')).to_have_count(30)
    expect(page.locator('.metric strong').first).to_have_text('94.4%')
    page.locator('[data-day="9"]').click()
    expect(page.locator('#dialog-content')).to_contain_text('Absent in sample history')
    page.keyboard.press('Escape')
    expect(page.locator('#detail-dialog')).not_to_be_visible()
    expect(page.locator('[data-day="9"]')).to_be_focused()
    record('Calendar, drawer, Escape and focus restoration work')
    page.locator('[data-tab="today"]').click()
    page.locator('[data-action="scenario"]').click()
    page.locator('[data-scenario="missing"]').click()
    expect(page.locator('[data-event="bus"]')).to_contain_text('Awaiting record')
    expect(page.locator('[data-event="gate"]')).to_contain_text('08:10')
    assert 'recorded' not in page.locator('[data-event="bus"]').get_attribute('class')
    record('Earlier missing event stays unconfirmed despite gate entry')
    page.locator('[data-action="scenario"]').click()
    page.locator('[data-scenario="family"]').click()
    expect(page.locator('[data-event="bus"]')).to_contain_text('Not applicable')
    record('Family drop-off does not invent boarding')
    page.locator('[data-action="scenario"]').click()
    page.locator('[data-scenario="stale"]').click()
    expect(page.locator('.stale-banner')).to_be_visible()
    page.locator('[data-action="retry"]').click()
    expect(page.locator('.stale-banner')).to_have_count(0)
    expect(page.locator('[data-event="gate"]')).to_contain_text('Awaiting record')
    record('Retry removes stale warning without inventing record')
    page.locator('[data-action="reset"]').click()
    page.locator('[data-action="next"]').click()
    expect(page.locator('.status-title')).to_have_text('Return boarding')
    page.locator('[data-action="next"]').click()
    expect(page.locator('.status-title')).to_have_text('Handover recorded')
    expect(page.locator('[data-action="next"]')).to_be_disabled()
    page.locator('[data-tab="updates"]').click()
    expect(page.locator('#app-content')).to_contain_text('Handover recorded')
    record('Next event, completion guard and activity history work')
    page.locator('[data-tab="today"]').click()
    page.locator('#child-select').select_option('rohan')
    expect(page.locator('.status-title')).to_have_text('School entry recorded')
    expect(page.locator('[data-event="bus"]')).to_contain_text('Not applicable')
    record('Sample children retain independent records')
    page.locator('[data-role="teacher"]').click()
    expect(page.locator('.data-table tbody tr')).to_have_count(5)
    page.locator('#student-search').fill('Arjun')
    expect(page.locator('.data-table tbody tr')).to_have_count(1)
    page.locator('[data-student="S-002"]').check()
    page.locator('[data-action="review-attendance"]').click()
    page.locator('[data-action="confirm-attendance"]').click()
    expect(page.locator('.data-table tbody')).to_contain_text('Recorded')
    page.locator('#student-search').fill('not in this demo')
    expect(page.locator('.empty-state')).to_be_visible()
    record('Teacher search, empty state, review and confirmation work')
    page.locator('#student-search').fill('')
    page.locator('#app').screenshot(path=str(OUT/'teacher-dashboard.png'))
    page.locator('[data-role="school"]').click()
    expect(page.locator('.metric strong').nth(1)).to_have_text('55')
    page.locator('#route-search').fill('07')
    expect(page.locator('.data-table tbody tr')).to_have_count(1)
    page.locator('[data-route="Route 07"]').click()
    expect(page.locator('#dialog-content .mini-map-caption')).to_contain_text('Route 07 / Bus B')
    expect(page.locator('#dialog-content')).to_contain_text('Update unavailable')
    page.keyboard.press('Escape')
    record('School filters and route-specific details work')
    page.locator('[data-action="reset"]').click()
    for width in [320,375,390,640,768,1024,1440]:
        page.set_viewport_size({'width':width,'height':900})
        page.wait_for_timeout(100)
        no_overflow(page,width)
    page.wait_for_timeout(4400)
    page.locator('#app').focus()
    page.set_viewport_size({'width':390,'height':844})
    page.evaluate('window.scrollTo({top:0,behavior:"instant"})')
    page.wait_for_timeout(150)
    page.screenshot(path=str(OUT/'mobile-hero.png'))
    page.locator('#app').screenshot(path=str(OUT/'mobile-dashboard.png'))
    page.locator('[data-event="gate"]').click()
    expect(page.locator('#detail-dialog')).to_be_visible()
    page.wait_for_timeout(400)  # Let the drawer transition settle before geometry checks.
    box = page.locator('#detail-dialog').bounding_box()
    assert abs(box['width'] - 390) < 1 and box['y'] > 0, box
    for _ in range(9):
        page.keyboard.press('Tab')
        assert page.evaluate('document.querySelector("dialog").contains(document.activeElement)')
    record('Mobile sheet traps keyboard focus')
    page.keyboard.press('Escape')
    page.emulate_media(reduced_motion='reduce')
    assert page.locator('.hero-bus').evaluate('el=>getComputedStyle(el).animationName') == 'none'
    record('Reduced motion disables decorative animation')
    assert errors == [], errors
    record('Zero browser JavaScript exceptions')
    offline = context.new_page()
    offline.set_content(html, wait_until='domcontentloaded')
    expect(offline.locator('.status-title')).to_have_text('Classroom check-in')
    offline.locator('[data-role="teacher"]').click()
    expect(offline.locator('.data-table tbody tr')).to_have_count(5)
    record('Portable HTML initializes without server dependencies')
    browser.close()
report={'passed':len(results),'checks':results,'browser':'Chromium','method':'Packaged preview loaded from local bytes; hosted navigation unavailable'}
(OUT/'browser-report.json').write_text(json.dumps(report,indent=2))
print(json.dumps(report,indent=2))
