import { Router } from "express";
import { z } from "zod";
import { RouteDirection, RouteStatus, UserRole, UserStatus, VehicleStatus } from "../../generated/prisma/client.js";
import { authenticate, requireRoles, roles } from "../../middleware/auth.js";
import { recordAudit } from "../../services/audit.js";
import { prisma } from "../../services/database.js";
import { ApiError } from "../../utils/api-error.js";
import { hashPassword } from "../../utils/auth-crypto.js";

const id = z.uuid();
const page = z.object({ limit: z.coerce.number().int().min(1).max(200).default(100) });
const userCreate = z.object({ email: z.email(), password: z.string().min(10).max(128), phone: z.string().max(32).optional(), role: z.enum(UserRole), status: z.enum(UserStatus).default(UserStatus.ACTIVE) });
const studentCreate = z.object({ studentCode: z.string().trim().min(1).max(50), firstName: z.string().trim().min(1).max(100), lastName: z.string().trim().min(1).max(100), classId: z.uuid().optional() });
const classCreate = z.object({ name: z.string().trim().min(1).max(80), section: z.string().trim().min(1).max(40), academicYear: z.string().trim().min(4).max(30) });
const vehicleCreate = z.object({ registrationNumber: z.string().trim().min(2).max(40), label: z.string().trim().min(1).max(80), capacity: z.number().int().min(1).max(150), status: z.enum(VehicleStatus).default(VehicleStatus.ACTIVE) });
const routeCreate = z.object({ name: z.string().trim().min(1).max(100), vehicleId: z.uuid().optional(), status: z.enum(RouteStatus).default(RouteStatus.ACTIVE), stops: z.array(z.object({ name: z.string().trim().min(1).max(120), latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), sequence: z.number().int().min(1), scheduledTime: z.string().max(20).optional() })).max(100).default([]) });
const guardianSchema = z.object({ userId: z.uuid(), studentId: z.uuid(), relationship: z.string().trim().min(1).max(80), authorisedPickup: z.boolean().default(false) });
const teacherClassSchema = z.object({ userId: z.uuid(), classId: z.uuid() });
const studentRouteSchema = z.object({ studentId: z.uuid(), routeId: z.uuid(), stopId: z.uuid().optional(), direction: z.enum(RouteDirection).default(RouteDirection.BOTH) });
const transportAssignmentSchema = z.object({ userId: z.uuid(), routeId: z.uuid(), vehicleId: z.uuid().optional() });

function auditContext(request: { auth?: { schoolId: string; userId: string }; id?: unknown; ip?: string }) {
  return { schoolId: request.auth!.schoolId, actorUserId: request.auth!.userId, requestId: String(request.id ?? ""), ...(request.ip ? { ipAddress: request.ip } : {}) };
}

export function createAdminRouter(): Router {
  const router = Router();
  router.use(authenticate, requireRoles(roles.ADMIN));

  router.get("/users", async (request, response, next) => { try {
    const query=page.parse(request.query); const users=await prisma.user.findMany({where:{schoolId:request.auth!.schoolId},select:{id:true,email:true,phone:true,role:true,status:true,createdAt:true,updatedAt:true},orderBy:{email:"asc"},take:query.limit}); response.json({users});
  } catch(error){next(error);} });

  router.post("/users", async (request, response, next) => { try {
    const input=userCreate.parse(request.body),email=input.email.toLowerCase(); if(await prisma.user.findUnique({where:{email},select:{id:true}}))throw new ApiError(409,"EMAIL_IN_USE","An account already uses this email.");
    const user=await prisma.user.create({data:{schoolId:request.auth!.schoolId,email,passwordHash:await hashPassword(input.password),role:input.role,status:input.status,...(input.phone?{phone:input.phone}:{})}});
    await recordAudit({...auditContext(request),action:"USER_CREATED",entityType:"User",entityId:user.id,newValue:{email:user.email,role:user.role,status:user.status}});
    response.status(201).json({user:{id:user.id,email:user.email,phone:user.phone,role:user.role,status:user.status}});
  } catch(error){next(error);} });

  router.patch("/users/:userId/status", async (request,response,next)=>{ try {
    const userId=id.parse(request.params.userId); const {status}=z.object({status:z.enum(UserStatus)}).parse(request.body); const existing=await prisma.user.findFirst({where:{id:userId,schoolId:request.auth!.schoolId}});
    if(!existing)throw new ApiError(404,"USER_NOT_FOUND","User was not found."); if(userId===request.auth!.userId&&status===UserStatus.DISABLED)throw new ApiError(400,"SELF_DISABLE_FORBIDDEN","You cannot disable your own active admin session.");
    const user=await prisma.user.update({where:{id:userId},data:{status,...(status===UserStatus.DISABLED?{tokenVersion:{increment:1}}:{})}}); if(status===UserStatus.DISABLED)await prisma.refreshSession.updateMany({where:{userId,revokedAt:null},data:{revokedAt:new Date()}});
    await recordAudit({...auditContext(request),action:"USER_STATUS_CHANGED",entityType:"User",entityId:userId,oldValue:{status:existing.status},newValue:{status}}); response.json({user:{id:user.id,email:user.email,role:user.role,status:user.status}});
  } catch(error){next(error);} });

  router.get("/students", async (request,response,next)=>{try{const query=page.parse(request.query);const students=await prisma.student.findMany({where:{schoolId:request.auth!.schoolId},include:{classroom:true},orderBy:[{firstName:"asc"},{lastName:"asc"}],take:query.limit});response.json({students});}catch(error){next(error);}});
  router.post("/students", async (request,response,next)=>{try{const input=studentCreate.parse(request.body);if(input.classId){const classroom=await prisma.classroom.findFirst({where:{id:input.classId,schoolId:request.auth!.schoolId},select:{id:true}});if(!classroom)throw new ApiError(400,"INVALID_CLASS","Class does not belong to this school.");}const student=await prisma.student.create({data:{schoolId:request.auth!.schoolId,studentCode:input.studentCode,firstName:input.firstName,lastName:input.lastName,...(input.classId?{classId:input.classId}:{})}});await recordAudit({...auditContext(request),action:"STUDENT_CREATED",entityType:"Student",entityId:student.id,newValue:{studentCode:student.studentCode,classId:student.classId}});response.status(201).json({student});}catch(error){next(error);}});
  router.get("/classes",async(request,response,next)=>{try{const classes=await prisma.classroom.findMany({where:{schoolId:request.auth!.schoolId},orderBy:[{academicYear:"desc"},{name:"asc"},{section:"asc"}]});response.json({classes});}catch(error){next(error);}});
  router.post("/classes",async(request,response,next)=>{try{const input=classCreate.parse(request.body);const classroom=await prisma.classroom.create({data:{schoolId:request.auth!.schoolId,...input}});await recordAudit({...auditContext(request),action:"CLASS_CREATED",entityType:"Classroom",entityId:classroom.id,newValue:{name:classroom.name,section:classroom.section,academicYear:classroom.academicYear}});response.status(201).json({classroom});}catch(error){next(error);}});

  router.post("/guardians",async(request,response,next)=>{try{const input=guardianSchema.parse(request.body);const[user,student]=await Promise.all([prisma.user.findFirst({where:{id:input.userId,schoolId:request.auth!.schoolId,role:UserRole.PARENT}}),prisma.student.findFirst({where:{id:input.studentId,schoolId:request.auth!.schoolId}})]);if(!user||!student)throw new ApiError(400,"INVALID_GUARDIAN_LINK","Parent user and student must belong to this school.");const guardian=await prisma.guardian.upsert({where:{userId_studentId:{userId:input.userId,studentId:input.studentId}},update:{relationship:input.relationship,authorisedPickup:input.authorisedPickup,active:true},create:input});await recordAudit({...auditContext(request),action:"GUARDIAN_LINK_UPSERTED",entityType:"Guardian",entityId:guardian.id,newValue:{userId:input.userId,studentId:input.studentId,authorisedPickup:input.authorisedPickup}});response.status(201).json({guardian});}catch(error){next(error);}});
  router.post("/teacher-class-assignments",async(request,response,next)=>{try{const input=teacherClassSchema.parse(request.body);const[user,classroom]=await Promise.all([prisma.user.findFirst({where:{id:input.userId,schoolId:request.auth!.schoolId,role:UserRole.TEACHER}}),prisma.classroom.findFirst({where:{id:input.classId,schoolId:request.auth!.schoolId}})]);if(!user||!classroom)throw new ApiError(400,"INVALID_TEACHER_CLASS_ASSIGNMENT","Teacher and class must belong to this school.");const assignment=await prisma.teacherClass.upsert({where:{userId_classId:input},update:{active:true},create:input});await recordAudit({...auditContext(request),action:"TEACHER_CLASS_ASSIGNED",entityType:"TeacherClass",entityId:assignment.id,newValue:input});response.status(201).json({assignment});}catch(error){next(error);}});

  router.get("/vehicles",async(request,response,next)=>{try{const vehicles=await prisma.vehicle.findMany({where:{schoolId:request.auth!.schoolId},orderBy:{label:"asc"}});response.json({vehicles});}catch(error){next(error);}});
  router.post("/vehicles",async(request,response,next)=>{try{const input=vehicleCreate.parse(request.body);const vehicle=await prisma.vehicle.create({data:{schoolId:request.auth!.schoolId,...input}});await recordAudit({...auditContext(request),action:"VEHICLE_CREATED",entityType:"Vehicle",entityId:vehicle.id,newValue:{label:vehicle.label,registrationNumber:vehicle.registrationNumber}});response.status(201).json({vehicle});}catch(error){next(error);}});
  router.get("/routes",async(request,response,next)=>{try{const routes=await prisma.route.findMany({where:{schoolId:request.auth!.schoolId},include:{vehicle:true,stops:{orderBy:{sequence:"asc"}}},orderBy:{name:"asc"}});response.json({routes});}catch(error){next(error);}});
  router.post("/routes",async(request,response,next)=>{try{const input=routeCreate.parse(request.body);if(input.vehicleId&&!await prisma.vehicle.findFirst({where:{id:input.vehicleId,schoolId:request.auth!.schoolId}}))throw new ApiError(400,"INVALID_VEHICLE","Vehicle does not belong to this school.");const route=await prisma.route.create({data:{schoolId:request.auth!.schoolId,name:input.name,status:input.status,...(input.vehicleId?{vehicleId:input.vehicleId}:{}),stops:{create:input.stops.map(stop=>({name:stop.name,latitude:stop.latitude,longitude:stop.longitude,sequence:stop.sequence,...(stop.scheduledTime?{scheduledTime:stop.scheduledTime}:{})}))}},include:{stops:true,vehicle:true}});await recordAudit({...auditContext(request),action:"ROUTE_CREATED",entityType:"Route",entityId:route.id,newValue:{name:route.name,vehicleId:route.vehicleId}});response.status(201).json({route});}catch(error){next(error);}});

  router.post("/student-route-assignments",async(request,response,next)=>{try{const input=studentRouteSchema.parse(request.body);const[student,route]=await Promise.all([prisma.student.findFirst({where:{id:input.studentId,schoolId:request.auth!.schoolId}}),prisma.route.findFirst({where:{id:input.routeId,schoolId:request.auth!.schoolId}})]);if(!student||!route)throw new ApiError(400,"INVALID_ROUTE_ASSIGNMENT","Student and route must belong to this school.");if(input.stopId&&!await prisma.routeStop.findFirst({where:{id:input.stopId,routeId:input.routeId}}))throw new ApiError(400,"INVALID_ROUTE_STOP","Stop does not belong to this route.");const assignment=await prisma.studentRouteAssignment.upsert({where:{studentId_routeId_direction:{studentId:input.studentId,routeId:input.routeId,direction:input.direction}},update:{active:true,...(input.stopId?{stopId:input.stopId}:{stopId:null})},create:{studentId:input.studentId,routeId:input.routeId,direction:input.direction,...(input.stopId?{stopId:input.stopId}:{})}});await recordAudit({...auditContext(request),action:"STUDENT_ROUTE_ASSIGNED",entityType:"StudentRouteAssignment",entityId:assignment.id,newValue:{studentId:input.studentId,routeId:input.routeId,direction:input.direction,stopId:input.stopId??null}});response.status(201).json({assignment});}catch(error){next(error);}});
  router.post("/transport-assignments",async(request,response,next)=>{try{const input=transportAssignmentSchema.parse(request.body);const[user,route]=await Promise.all([prisma.user.findFirst({where:{id:input.userId,schoolId:request.auth!.schoolId,role:UserRole.TRANSPORT}}),prisma.route.findFirst({where:{id:input.routeId,schoolId:request.auth!.schoolId}})]);if(!user||!route)throw new ApiError(400,"INVALID_TRANSPORT_ASSIGNMENT","Transport user and route must belong to this school.");if(input.vehicleId&&!await prisma.vehicle.findFirst({where:{id:input.vehicleId,schoolId:request.auth!.schoolId}}))throw new ApiError(400,"INVALID_VEHICLE","Vehicle does not belong to this school.");const assignment=await prisma.transportAssignment.upsert({where:{userId_routeId:{userId:input.userId,routeId:input.routeId}},update:{active:true,...(input.vehicleId?{vehicleId:input.vehicleId}:{vehicleId:null})},create:{userId:input.userId,routeId:input.routeId,...(input.vehicleId?{vehicleId:input.vehicleId}:{})}});await recordAudit({...auditContext(request),action:"TRANSPORT_ROUTE_ASSIGNED",entityType:"TransportAssignment",entityId:assignment.id,newValue:{userId:input.userId,routeId:input.routeId,vehicleId:input.vehicleId??null}});response.status(201).json({assignment});}catch(error){next(error);}});
  return router;
}
